---
title: "Imputaion"
author: "Xiaolei Li"
date: "2025-03-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#install.packages("PhysicalActivity")
#install.packages("tidyverse")
#install.packages("broom.mixed")

library(readxl)
library(haven)
library(PhysicalActivity)
library(tidyverse)
library(lubridate)
library(scales)
library(dplyr)
library(nlme)
library(mice)
library(lme4)
library(broom.mixed) # pooling results for mixed model 
```

```{r}
data <- read_excel("/Users/lixiaolei/Desktop/Hsu_group/accelerameter/thesis_writing/data/NHANES2005_2006Pure.xlsx")
data_demo <- read_xpt("/Users/lixiaolei/Desktop/Hsu_group/accelerameter/thesis_writing/data/DEMO_D.XPT")
data_BMI <- read_xpt("/Users/lixiaolei/Desktop/Hsu_group/accelerameter/thesis_writing/data/BMX_D.XPT")
```



```{r}
# illustrate the activity change

# convert time format
data$Time1 <- format(data$Time, "%H:00")

# compute activity intensity ave per minute
sum_inten_hour <- data %>% filter(data$SEQN == 31128, PAXDAY %in% c(1,2,3)) %>% group_by(PAXDAY, Time1) %>% summarise(sum_intensity = sum(PAXINTEN)/60)

#sum_inten_hour$Time1 <- as.numeric(sum_inten_hour$Time1)

sum_inten_hour <- sum_inten_hour %>%
  arrange(PAXDAY, Time1) %>%
  filter(!is.na(Time1)) %>%
  mutate(Time_Ordered = factor(paste(PAXDAY, Time1, sep = "_"), 
                               levels = unique(paste(PAXDAY, Time1, sep = "_")))) 

breaks_seq <- seq(1, nrow(sum_inten_hour), by = 5)
labels_seq <- substr(as.character(sum_inten_hour$Time_Ordered[breaks_seq]), 3, 7)

ggplot(sum_inten_hour, aes(x = Time_Ordered, y = sum_intensity, color = factor(PAXDAY))) + 
  geom_point(shape = 21, size = 2, stroke = 1) +
  geom_line(group = 1) +  
  scale_x_discrete(
  breaks = sum_inten_hour$Time_Ordered[breaks_seq],  
  labels = labels_seq ) +
  scale_y_continuous(breaks = seq(0, 1250, 250), limits = c(0,1250)) +
  labs(x = "Time", y = "Activity Intensity Average per Minute", color = "Day") +  
  scale_color_manual(values = c("aquamarine3", "coral", "darkgoldenrod1"),
                     labels = c("Sunday", "Monday", "Tuesday")) +  
  theme_bw() +
  
  theme(axis.text.x = element_text(angle = 30, hjust = 1),
        legend.title = element_blank(),
        panel.border = element_blank(),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank()
        ) 
```



```{r}
# simulate missing data

mydata <-data_1 %>% filter(SEQN %in% first_104)
mydata$index <- seq(1: nrow(mydata))

group_proportions <- c(0.5, 0.3, 0.1, 0.1)
group_missingness <- c(0.2, 0.3, 0.4, 0.5)

MCAR <- function(mydata, group_proportions, group_missingness){
  
  modified_data <- list()
  
  # get unique SEQN values
  y <- unique(mydata$SEQN)
  
  # sample patient groups based on proportions
  patient_group <- sample(x = seq_along(group_proportions), 
                          size = length(y), replace = TRUE, prob = group_proportions)
  
  # create a group assignment data frame
  group_assignment <- data.frame(SEQN = y, Group = patient_group)
  
  # assign missingness percentages to the groups
  
  group_assignment$group_missingness <- group_missingness[group_assignment$Group]
  
  # merge group assignment with the main data
  mydata <- merge(mydata, group_assignment, by = "SEQN")
  
  # loop through each unique SEQN
  for (seqn in unique(mydata$SEQN)){
    
      # current SEQN
      one_patient_nw_w <- mydata %>% filter(SEQN == seqn) %>% arrange(PAXN)
      one_patient <- mydata %>% filter(SEQN == seqn) %>% filter(wearing == 'w') %>% arrange(PAXN)
      
      total_wear_rows <- nrow(one_patient)
      
      # get the missingness for the current group
      desired_percent <- one_patient$group_missingness[1] 
      
      nrows_to_sample <- round(total_wear_rows * desired_percent)
      
      total_sampled_rows <- 0
      
      available_index <- 1:total_wear_rows 
      
      # initialize sampled blocks
      sampled_block <- list()

      # loop to sample rows 
      while (total_sampled_rows <= nrows_to_sample) {
      
        # sample block size
        block_size <- round(rnorm(1, 6 * 60, 2 * 60))   
        
        # sample starting index and calculate the end index
        start_index <- sample(available_index, 1)
        end_index <- min(total_wear_rows, start_index + block_size -1)
      
        # extract the block  
        block <- one_patient[start_index:end_index, ]
      
        #if this is the first block
        if(length(sampled_block) == 0){
          sampled_block[[length(sampled_block) + 1]] <- block
          total_sampled_rows <- total_sampled_rows + nrow(block)
            
          # remove used indices to prevent overlap
          used_indices <- start_index:(start_index + nrow(block) - 1)
          available_index <- setdiff(available_index, used_indices)
        } else {
          if((sum(sapply(sampled_block,nrow)) + nrow(block)) < nrows_to_sample){
            sampled_block[[length(sampled_block) + 1]] <- block
            total_sampled_rows <- total_sampled_rows + nrow(block)
            
            # remove used indices to prevent overlap
            used_indices <- start_index:(start_index + nrow(block) - 1)
            available_index <- setdiff(available_index, used_indices)
          } else {
            break
          }
        }  
    }
      # combine all the sampled blocks into one data frame
      final_sampled_df <- do.call(rbind, sampled_block)
      
      # mark the selected samples with missing values
      one_patient_nw_w$PAXINTEN[one_patient_nw_w$index %in% final_sampled_df$index] <- NA
      
      # add the final_sample to the modified_data list
      modified_data[[length(modified_data) + 1]] <- one_patient_nw_w
  }
  
  # Combine all modified data into a single data frame
  modified_data_df <- do.call(rbind, modified_data)
  
  return(modified_data_df)
} 

data_missing <- MCAR(mydata, group_proportions, group_missingness)


# plot a missing day
test <- data_missing %>% filter(SEQN == 31151) %>% filter(PAXDAY == 3)

ggplot(test, aes(x = Time, y = PAXINTEN)) +
  geom_rect(aes(xmin = Time, xmax = lead(Time, default = last(Time)), 
                ymin = 0, ymax = max(PAXINTEN, na.rm = TRUE), 
                fill = factor(is.na(PAXINTEN))), alpha = 0.6) + 
  scale_fill_manual(values = c("TRUE" = "lightblue", "FALSE" = "NA")) + 
  geom_line() +
  labs(x = "Time", y = "Activity Intensity per Minute", fill = "Missing Data") +
  theme_minimal() +
  scale_x_datetime(date_labels = "%H:%M", date_breaks = "2 hour") +
  guides(fill = "none") 

# plot a complete day
original <- mydata %>% filter(mydata$SEQN == 31151) %>% filter(PAXDAY == 3)

ggplot(original, aes(x = Time, y = PAXINTEN)) +
  geom_line() +  
  labs(x = "Time", y = "Activity Intensity per Minute") +
  theme_minimal() +   
  scale_x_datetime(date_labels = "%H:%M", date_breaks = "2 hour")  

```



```{r}
# PMM

pmm_impute <- function(mydata_incomplete_2, n.imp = 5) {
  
  # define predictor and response
  x <- mydata_incomplete_2[,c("BMXBMI", "RIDAGEYR", "RIAGENDR", "sunday_indicator", "saturday_indicator", "total_wear_hour")]
  
  y <- mydata_incomplete_2$sum_PAXINTEN_1
  
  # identify observed and missing values
  ry <- !is.na(y) # non-NA rows
  wy <- !ry # NA rows
  
  xobs <- x[ry,] 
  yobs <- y[ry] 
  
                               
  # fit linear mixed model. (incomplete - NA or complete??)
  fit <- lmer(sum_PAXINTEN ~ 1 + BMXBMI + RIDAGEYR + RIAGENDR + sunday_indicator + saturday_indicator +      total_wear_hour + (1 + total_wear_hour | SEQN), data = mydata_complete_1)

  # extract fixed effects 
  beta_hat <- fixef(fit)
  
  # extract variance-covariance matrix of beta
  vcov_beta <- vcov(fit) 
  
  # extract variance components
  vc <- VarCorr(fit)
  
  # random intercept sd
  tau0_hat <- attr(vc$SEQN, "stddev")[1]
  
  # random total_wear_hour sd
  tau_wear_hat <- attr(vc$SEQN, "stddev")[2]
  
  # residual sd
  sigma_hat <- sigma(fit)

  df <- nrow(fit@frame) - length(fit@beta)  
  
  
  # generate multiple imputations
  imputed_datasets <-list()

  
  for (j in 1:n.imp) {
      
   # draw a random sample for the residual error
   sigma2_star <- df * sigma_hat / rchisq(1, df)  
   
   # rescale the covariance matrix to the new draw of sigma
   covmat <- sigma2_star * (vcov_beta/sigma_hat)
   rv <- t(chol(covmat))
  
   # draw random sample for the beta coefficients
   beta_star <- beta_hat + rv %*% rnorm(ncol(rv))
    
    x_all <- model.matrix(~ 1 + BMXBMI + RIDAGEYR + RIAGENDR + sunday_indicator + saturday_indicator + total_wear_hour, data = mydata_incomplete_2)
    
    mydata_incomplete_2$prediction <- x_all %*% beta_star[1:7]
    
    y_pred_obs <- mydata_incomplete_2$prediction[ry] # predicted values for observed y
    y_pred_mis <- mydata_incomplete_2$prediction[wy] # predicted values for missing y
    
    # randomly draw among indices of the 5 closest values
    y_pred_pmm <- matchindex(y_pred_obs, y_pred_mis, k=5) 
    
    y_imputed <- y
    y_imputed[wy] <- yobs[y_pred_pmm]  # assign imputed values
  
     # store the imputed dataset
    imputed_datasets[[j]] <- y_imputed
  }
  
  # return a list of imputed datasets
  return(imputed_datasets)
}

result <- pmm_impute(mydata_incomplete_2,n.imp = 5)



```